const fs = require('fs');
let c = fs.readFileSync('index.html', 'utf8');

// 1. renderManageProducts map
let target1 = 'return `<tr><td><span class="badge bg-dark" style="font-size:0.7rem;">${p.purchaseNo || \x27-\x27}</span></td><td>${dateStr}</td><td class="text-start">${p.name}</td><td class="text-muted small">${p.supplier || \x27-\x27}</td><td>${p.brand}</td><td>฿${p.cost.toLocaleString()}</td><td class="text-success">฿${p.actualPrice.toLocaleString()}</td><td><span class="fw-bold ${p.stock <= 0 ? \x27text-danger\x27 : \x27text-dark\x27}">${p.stock}</span></td><td>${fbBtn}</td><td><button class="btn btn-sm btn-outline-warning me-1" onclick="editProduct(\x27${p.id}\x27,\x27${p.updatedAt}\x27,\x27${p.name}\x27,\x27${p.brand}\x27,${p.cost},${p.actualPrice},${p.stock},\x27${p.fbLink}\x27,\x27${p.purchaseNo}\x27,\x27${p.supplier}\x27,\x27${p.serialNumber}\x27,\x27${p.cpu}\x27,\x27${p.ram}\x27,\x27${p.gpu}\x27,\x27${p.screenSize}\x27,\x27${p.color}\x27,\x27${p.warranty}\x27)"><i class="fa-solid fa-pen"></i></button><button class="btn btn-sm btn-outline-secondary" onclick="printProductDetail(\x27${p.id}\x27)" title="พิมพ์ข้อมูลสินค้า"><i class="fa-solid fa-print"></i></button><button class="btn btn-sm btn-outline-danger ms-1" onclick="deleteProduct(\x27${p.id}\x27)" title="ลบสินค้า"><i class="fa-solid fa-trash"></i></button></td></tr>`;';

let rep1 = 'return `<tr><td><input type="checkbox" class="form-check-input product-checkbox" value="${p.id}"></td><td><span class="badge bg-dark" style="font-size:0.7rem;">${p.purchaseNo || \x27-\x27}</span></td><td>${dateStr}</td><td class="text-start">${p.name}</td><td class="text-muted small">${p.supplier || \x27-\x27}</td><td>${p.brand}</td><td>฿${p.cost.toLocaleString()}</td><td class="text-success">฿${p.actualPrice.toLocaleString()}</td><td><span class="fw-bold ${p.stock <= 0 ? \x27text-danger\x27 : \x27text-dark\x27}">${p.stock}</span></td><td>${fbBtn}</td><td><button class="btn btn-sm btn-outline-warning me-1" onclick="editProduct(\x27${p.id}\x27,\x27${p.updatedAt}\x27,\x27${p.name}\x27,\x27${p.brand}\x27,${p.cost},${p.actualPrice},${p.stock},\x27${p.fbLink}\x27,\x27${p.purchaseNo}\x27,\x27${p.supplier}\x27,\x27${p.serialNumber}\x27,\x27${p.cpu}\x27,\x27${p.ram}\x27,\x27${p.gpu}\x27,\x27${p.screenSize}\x27,\x27${p.color}\x27,\x27${p.warranty}\x27)"><i class="fa-solid fa-pen"></i></button><button class="btn btn-sm btn-outline-secondary" onclick="printProductDetail(\x27${p.id}\x27)" title="พิมพ์ข้อมูลสินค้า"><i class="fa-solid fa-print"></i></button><button class="btn btn-sm btn-outline-danger ms-1" onclick="deleteProduct(\x27${p.id}\x27)" title="ลบสินค้า"><i class="fa-solid fa-trash"></i></button></td></tr>`;';

c = c.replace(target1, rep1);

// colspan
c = c.replace('colspan="10" class="text-muted">ไม่มีสินค้า', 'colspan="11" class="text-muted">ไม่มีสินค้า');

// 2. Insert printSelectedProductsSection
let target2 = `<div class="text-center mt-4 small text-muted">เอกสารออกโดยระบบจัดการคลังสินค้า หจก. โน๊ตบุ๊ค ไอทีอุดร — พิมพ์อัตโนมัติ</div>\r\n      </div>\r\n    </div>\r\n  </div>`;
if(!c.includes(target2)) {
  target2 = target2.replace(/\r\n/g, '\n');
}

let rep2 = `<div class="text-center mt-4 small text-muted">เอกสารออกโดยระบบจัดการคลังสินค้า หจก. โน๊ตบุ๊ค ไอทีอุดร — พิมพ์อัตโนมัติ</div>\n      </div>\n    </div>\n\n    <!-- Print Selected Products Layout -->\n    <div id="printSelectedProductsSection" class="print-wrapper-box d-none" style="padding: 20px; background:#fff; color:#000;">\n      <div class="invoice-box">\n        <div class="row mb-4 pb-3" style="border-bottom: 3px solid #f97316;">\n          <div class="col-7 text-start">\n            <h4 class="fw-bold m-0" style="color:#0f172a;">ห้างหุ้นส่วนจำกัด โน๊ตบุ๊ค ไอทีอุดร</h4>\n            <p class="small m-0">ทะเบียนนิติบุคคลเลขที่ 0413569001497 (สำนักงานใหญ่)<br>ที่อยู่: 119/138 มบ.พีเคธานี 4 ม.5 ถ.อุดรธานี-หนองคาย ต.หมู่ม่น อ.เมือง จ.อุดรธานี ปณ.41000<br>โทรศัพท์: 0908422774</p>\n          </div>\n          <div class="col-5 text-end">\n            <h3 class="fw-bold m-0" style="color:#f97316;"><i class="fa-solid fa-boxes-stacked"></i> รายการสินค้าคลังที่เลือก</h3>\n            <p class="m-0 mt-2"><strong>วันที่พิมพ์:</strong> <span id="psPrintDate"></span></p>\n          </div>\n        </div>\n\n        <table class="table table-bordered align-middle text-center" style="font-size: 0.95rem;" id="psProductsTable">\n          <thead style="background:#0f172a; color:#fff;">\n            <tr>\n              <th>เลขที่ซื้อเข้า</th>\n              <th>วันที่ลงรายการ</th>\n              <th>ชื่อสินค้า / รุ่น</th>\n              <th>ซื้อจาก</th>\n              <th>ยี่ห้อ</th>\n              <th>S/N</th>\n              <th>ทุน</th>\n              <th>ขาย</th>\n              <th>คงเหลือ</th>\n            </tr>\n          </thead>\n          <tbody id="psProductsTableBody">\n          </tbody>\n        </table>\n\n        <div class="row mt-5 text-center small pt-4" style="border-top: 1px dashed #cbd5e1;">\n          <div class="col-4"><br><br>...................................................<br>ผู้ตรวจสอบคลัง</div>\n          <div class="col-4"></div>\n          <div class="col-4"><br><br>...................................................<br>ผู้จัดการ / เจ้าของกิจการ</div>\n        </div>\n        <div class="text-center mt-4 small text-muted">เอกสารออกโดยระบบจัดการคลังสินค้า หจก. โน๊ตบุ๊ค ไอทีอุดร — พิมพ์อัตโนมัติ</div>\n      </div>\n    </div>\n  </div>`;
c = c.replace(target2, rep2);

// 3. Insert JS functions
let target3 = `setTimeout(() => { document.getElementById('printProductDetailSection').classList.add('d-none'); }, 1000);\n    }`;
if(!c.includes(target3)) {
  target3 = `setTimeout(() => { document.getElementById('printProductDetailSection').classList.add('d-none'); }, 1000);\r\n    }`;
}
let rep3 = `setTimeout(() => { document.getElementById('printProductDetailSection').classList.add('d-none'); }, 1000);\n    }\n\n    function toggleSelectAllProducts(el) {\n      let checkboxes = document.querySelectorAll('.product-checkbox');\n      checkboxes.forEach(cb => cb.checked = el.checked);\n    }\n\n    function printSelectedProducts() {\n      let selectedIds = Array.from(document.querySelectorAll('.product-checkbox:checked')).map(cb => cb.value);\n      if (selectedIds.length === 0) {\n        Swal.fire('แจ้งเตือน', 'กรุณาเลือกสินค้าอย่างน้อย 1 รายการเพื่อพิมพ์', 'warning');\n        return;\n      }\n      executePrintSelected(selectedIds);\n    }\n\n    function printAllProducts() {\n      let allIds = Array.from(document.querySelectorAll('.product-checkbox')).map(cb => cb.value);\n      if (allIds.length === 0) {\n        Swal.fire('แจ้งเตือน', 'ไม่มีสินค้าที่จะพิมพ์', 'warning');\n        return;\n      }\n      executePrintSelected(allIds);\n    }\n\n    function executePrintSelected(ids) {\n      let today = new Date();\n      let printDate = \`\${String(today.getDate()).padStart(2,'0')}/\${String(today.getMonth()+1).padStart(2,'0')}/\${today.getFullYear()}\`;\n      document.getElementById('psPrintDate').innerText = printDate;\n\n      let tbody = document.getElementById('psProductsTableBody');\n      tbody.innerHTML = '';\n      \n      let itemsToPrint = globalProducts.filter(p => ids.includes(String(p.id)));\n      \n      let html = '';\n      itemsToPrint.forEach(p => {\n        let dateStr = p.updatedAt ? formatDateToTH(p.updatedAt.split('T')[0]) : "-";\n        html += \`<tr>\n          <td>\${p.purchaseNo || '-'}</td>\n          <td>\${dateStr}</td>\n          <td class="text-start">\${p.name}</td>\n          <td class="text-muted small">\${p.supplier || '-'}</td>\n          <td>\${p.brand}</td>\n          <td>\${p.serialNumber || '-'}</td>\n          <td>฿\${p.cost.toLocaleString()}</td>\n          <td class="text-success fw-bold">฿\${p.actualPrice.toLocaleString()}</td>\n          <td class="\${p.stock <= 0 ? 'text-danger fw-bold' : ''}">\${p.stock}</td>\n        </tr>\`;\n      });\n      tbody.innerHTML = html;\n\n      document.getElementById('printSelectedProductsSection').classList.remove('d-none');\n      window.print();\n      setTimeout(() => { document.getElementById('printSelectedProductsSection').classList.add('d-none'); }, 1000);\n    }`;
c = c.replace(target3, rep3);

fs.writeFileSync('index.html', c);
console.log('done');
